# Used for development
development:
  adapter: postgresql
  encoding: unicode
  database: theerrorlogs_development
  pool: 5
  username: benclarke
  password:
  host: :localhost

# Used for testing
test:
  adapter: postgresql
  encoding: unicode
  database: theerrorlogs_test
  pool: 5
  username: benclarke
  password:
  host: :localhost
